global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "kafka-brokers"
    static_configs:
      - targets:
          - "kafka-controller-1:9404"
          - "kafka-broker-2:9404"
          - "kafka-broker-3:9404"

  - job_name: "kafka-connect"
    static_configs:
      - targets:
          - "kafka-connect:9406"

  - job_name: "schema-registry"
    static_configs:
      - targets:
          - "schema-registry:9405"
